// This file is automatically generated by qtc from "vast.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line vast.qtpl:1
package qtpl

//line vast.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line vast.qtpl:1
import v "github.com/Jun-Chang/vast-xml-test/vast"

//line vast.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line vast.qtpl:3
func StreamXMLFromQuickTemplate(qw422016 *qt422016.Writer, vast *v.Vast) {
	//line vast.qtpl:3
	qw422016.N().S(`<VAST version="`)
	//line vast.qtpl:4
	qw422016.E().S(vast.Version)
	//line vast.qtpl:4
	qw422016.N().S(`">`)
	//line vast.qtpl:5
	for _, ad := range vast.Ads {
		//line vast.qtpl:5
		qw422016.N().S(`<Ad>`)
		//line vast.qtpl:7
		inLine := ad.InLine

		//line vast.qtpl:7
		qw422016.N().S(`<InLine><AdSystem version="`)
		//line vast.qtpl:9
		qw422016.E().S(inLine.AdSystem.Version)
		//line vast.qtpl:9
		qw422016.N().S(`">`)
		//line vast.qtpl:9
		qw422016.E().S(inLine.AdSystem.Name)
		//line vast.qtpl:9
		qw422016.N().S(`</AdSystem><AdTitle>`)
		//line vast.qtpl:10
		qw422016.E().S(inLine.AdTitle)
		//line vast.qtpl:10
		qw422016.N().S(`</AdTitle><Impression id="`)
		//line vast.qtpl:11
		qw422016.E().S(inLine.Impression.ID)
		//line vast.qtpl:11
		qw422016.N().S(`"><![CDATA[`)
		//line vast.qtpl:12
		qw422016.E().S(inLine.Impression.URI)
		//line vast.qtpl:12
		qw422016.N().S(`]]></Impression><Description>`)
		//line vast.qtpl:14
		qw422016.E().S(inLine.Description)
		//line vast.qtpl:14
		qw422016.N().S(`</Description><Error><![CDATA[`)
		//line vast.qtpl:16
		qw422016.E().S(inLine.Error.Text)
		//line vast.qtpl:16
		qw422016.N().S(`]]></Error><Extensions></Extensions><Creatives>`)
		//line vast.qtpl:20
		for _, creative := range inLine.Creatives {
			//line vast.qtpl:20
			qw422016.N().S(`<Creative>`)
			//line vast.qtpl:22
			linear := creative.Linear

			//line vast.qtpl:23
			videoClicks := linear.VideoClicks

			//line vast.qtpl:23
			qw422016.N().S(`<Linear><Duration>`)
			//line vast.qtpl:25
			qw422016.E().S(linear.Duration)
			//line vast.qtpl:25
			qw422016.N().S(`</Duration>`)
			//line vast.qtpl:26
			for _, mediaFile := range linear.MediaFiles {
				//line vast.qtpl:26
				qw422016.N().S(`<MediaFiles><MediaFile id="`)
				//line vast.qtpl:28
				qw422016.E().S(mediaFile.ID)
				//line vast.qtpl:28
				qw422016.N().S(`" delivery="`)
				//line vast.qtpl:28
				qw422016.E().S(mediaFile.Delivery)
				//line vast.qtpl:28
				qw422016.N().S(`" type="`)
				//line vast.qtpl:28
				qw422016.E().S(mediaFile.Type)
				//line vast.qtpl:28
				qw422016.N().S(`" width="`)
				//line vast.qtpl:28
				qw422016.N().D(mediaFile.Width)
				//line vast.qtpl:28
				qw422016.N().S(`" height="`)
				//line vast.qtpl:28
				qw422016.N().D(mediaFile.Height)
				//line vast.qtpl:28
				qw422016.N().S(`"><![CDATA[`)
				//line vast.qtpl:29
				qw422016.E().S(mediaFile.URI)
				//line vast.qtpl:29
				qw422016.N().S(`]]></MediaFile></MediaFiles>`)
				//line vast.qtpl:32
			}
			//line vast.qtpl:32
			qw422016.N().S(`<VideoClicks><ClickThrough id="`)
			//line vast.qtpl:34
			qw422016.E().S(videoClicks.ClickThrough.ID)
			//line vast.qtpl:34
			qw422016.N().S(`"><![CDATA[`)
			//line vast.qtpl:35
			qw422016.E().S(videoClicks.ClickThrough.URI)
			//line vast.qtpl:35
			qw422016.N().S(`]]></ClickThrough><ClickTracking id="`)
			//line vast.qtpl:37
			qw422016.E().S(videoClicks.ClickTracking.ID)
			//line vast.qtpl:37
			qw422016.N().S(`"><![CDATA[`)
			//line vast.qtpl:38
			qw422016.E().S(videoClicks.ClickTracking.URI)
			//line vast.qtpl:38
			qw422016.N().S(`]]></ClickTracking><CustomClick id="`)
			//line vast.qtpl:40
			qw422016.E().S(videoClicks.CustomClick.ID)
			//line vast.qtpl:40
			qw422016.N().S(`"><![CDATA[`)
			//line vast.qtpl:41
			qw422016.E().S(videoClicks.CustomClick.URI)
			//line vast.qtpl:41
			qw422016.N().S(`]]></CustomClick></VideoClicks><TrackingEvents>`)
			//line vast.qtpl:45
			for _, tracking := range linear.TrackingEvents {
				//line vast.qtpl:45
				qw422016.N().S(`<Tracking event="`)
				//line vast.qtpl:46
				qw422016.E().S(tracking.Event)
				//line vast.qtpl:46
				qw422016.N().S(`"><![CDATA[`)
				//line vast.qtpl:47
				qw422016.E().S(tracking.URI)
				//line vast.qtpl:47
				qw422016.N().S(`]]></Tracking>`)
				//line vast.qtpl:49
			}
			//line vast.qtpl:49
			qw422016.N().S(`</TrackingEvents></Linear></Creative>`)
			//line vast.qtpl:53
		}
		//line vast.qtpl:53
		qw422016.N().S(`</Creatives></InLine></Ad>`)
		//line vast.qtpl:57
	}
	//line vast.qtpl:57
	qw422016.N().S(`</VAST>`)
//line vast.qtpl:59
}

//line vast.qtpl:59
func WriteXMLFromQuickTemplate(qq422016 qtio422016.Writer, vast *v.Vast) {
	//line vast.qtpl:59
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line vast.qtpl:59
	StreamXMLFromQuickTemplate(qw422016, vast)
	//line vast.qtpl:59
	qt422016.ReleaseWriter(qw422016)
//line vast.qtpl:59
}

//line vast.qtpl:59
func XMLFromQuickTemplate(vast *v.Vast) string {
	//line vast.qtpl:59
	qb422016 := qt422016.AcquireByteBuffer()
	//line vast.qtpl:59
	WriteXMLFromQuickTemplate(qb422016, vast)
	//line vast.qtpl:59
	qs422016 := string(qb422016.B)
	//line vast.qtpl:59
	qt422016.ReleaseByteBuffer(qb422016)
	//line vast.qtpl:59
	return qs422016
//line vast.qtpl:59
}
